config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/home/about' => 'homes#about', as: 'about'
  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:index, :show, :edit, :update, :create,]
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  patch 'users/:id' => 'users#update', as: 'update_user'
  delete 'users/:id' => 'users#destroy', as: 'destroy_user'
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
  belongs_to :user

  def get_profile_image
    unless image.attached?
      file_path = Rails_root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :is_matching_login_user, only: [:edit, :update]

  def show
    @books = Book.all
    @book = Book.find(params[:id])
    @users = User.all
    @user = User.find(@book.user_id)
  end

  def index
    @users = User.all
    @user = User.find(current_user.id)
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @users = User.all
      @user = User.find(current_user.id)
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :image, :body, :user_id)
  end

  def is_matching_login_user
    book = Book.find(params[:id])
    user = User.find(book.user_id)
    unless user.id == current_user.id
      redirect_to books_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_sidebar.html.erb
<div class="col-md-3">

  <h2>User info</h2>

  <%= image_tag  user.get_profile_image(100,100) %>

  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>

      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>

  <div class="row">
    <%= link_to edit_user_path(current_user.id), class: 'btn btn-outline-secondary btn-block mt-4' do %>
      <i class="fas fa-user-cog" style="font-size: 1rem;"></i>
    <% end %>
  </div>

  <h2 class="mt-3">New book</h2>

  <%= form_with model: book do |f|%>

    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :body, "Opinion"%>
      <%= f.text_area :body, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.submit 'Create Book', class: 'btn  btn-success' %>
    </div>

  <% end %>
</div>

app/views/books/edit.html.erb
<div class="container mt-3">



  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>

      <% if @book.errors.any? %>
        <% if @book.errors.count == 1 %>
          <h3>1 error prohibited this obj from being saved:</h3>
        <% else %>
          <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
        <% end %>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <%= form_with model: @book, url:update_book_path(@book.id), method: :patch do |f|%>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :body, "Opinion" %>
          <%= f.text_area :body, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.submit 'Update Book', class: 'btn btn-success' %>
        </div>

      <% end %>

      <%= link_to "Show", book_path(params[:id]) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-sm-0 mt-3">

  <% if @book.errors.any? %>
    <% if @book.errors.count == 1 %>
      <h3>1 error prohibited this obj from being saved:</h3>
    <% else %>
      <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
    <% end %>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="row">

    <%= render 'sidebar', book: Book.new, user: @user %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>

      <table class="table table-hover table-inverse">

        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>

          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user_id) do %>
                  <%= image_tag  User.find(book.user_id).get_profile_image(80,80) %>
                <% end %>
              </td>

              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>

              <td>
                <%= book.body %>
              </td>
            </tr>

          <% end %>

        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container mt-3">

  <div class="row">

       <div class="col-md-3">

    <h2>User info</h2>

    <%= image_tag  @user.get_profile_image(100,100) %>

    <table class="table">
      <tbody>
        <tr>
          <th>name</th>
          <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
        </tr>
      </tbody>
    </table>

    <div class="row">
      <%= link_to edit_user_path(@user.id), class: 'btn btn-outline-secondary btn-block mt-4' do %>
        <i class="fas fa-user-cog" style="font-size: 1rem;"></i>
      <% end %>
    </div>

    <h2 class="mt-3">New book</h2>

      <%= form_with model: Book.new do |f|%>

        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :body, "Opinion"%>
          <%= f.text_area :body, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.submit 'Create Book', class: 'btn  btn-success' %>
        </div>

      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>

      <table class="table table-hover table-inverse">

        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user_id) do %>
                <%= image_tag  @user.get_profile_image(100,100) %>
                <br>
                <%= @user.name %>
              <% end %>
            </td>

            <td>
              <%= link_to book_path(@book.id) do %>
                <%= @book.title %>
              <% end %>
            </td>

            <td>
              <%= @book.body %>
            </td>

            <% if @book.user_id == current_user.id %>
              <td>
                <%= link_to "Edit", edit_book_path, class: 'btn btn-sm btn-success' %>
              </td>

              <td>
                <%= link_to "Destroy", destroy_book_path, method: :delete,
                "data-confirm" => "本当に削しますか？", class: 'btn btn-sm btn-danger' %>
              </td>
            <% end %>
          </tr>

        </tbody>
      </table>
    </div>
  </div>
</div>