config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/home/about' => 'homes#about', as: 'about'
  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:index, :show, :edit, :update, :create,]
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  patch 'users/:id' => 'users#update', as: 'update_user'
  delete 'users/:id' => 'users#destroy', as: 'destroy_user'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg bg-dark navbar-dark w-100">
        <div class="container">
          <a class="navbar-brand p-5px" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon "></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

              <% if user_signed_in? %>
              <li class="nav-link p-8px">
                <%= link_to user_path(current_user.id), class: 'd-flex align-items-center text-light text-decoration-none' do %>
                  <i class="fas fa-home"></i>&nbsp;Home
                <% end %>
              </li>
              <li class="nav-link p-8px">
                <%= link_to users_path, class: 'd-flex align-items-center text-light text-decoration-none' do %>
                  <i class="fas fa-users"></i>&nbsp;Users
                <% end %>
              </li>
              <li class="nav-link p-8px">
                <%= link_to books_path, class: 'd-flex align-items-center text-light text-decoration-none' do %>
                  <i class="fas fa-book-open"></i>&nbsp;Books
                <% end %>
              </li>
              <li class="nav-link p-8px">
                <%= link_to destroy_user_session_path, method: :delete, class: 'd-flex align-items-center text-light text-decoration-none' do %>
                  <i class="fas fa-sign-out-alt"></i>&nbsp;Log out
                <% end %>
              </li>
              <% else %>
              <li class="nav-link p-8px">
                <%= link_to root_path, class: 'd-flex align-items-center text-light text-decoration-none' do %>
                  <i class="fas fa-home"></i>&nbsp;Home
                <% end %>
              </li>
              <li class="nav-link p-8px">
                <%= link_to about_path, class: 'd-flex align-items-center text-light text-decoration-none' do %>
                  <i class="fas fa-link"></i>&nbsp;About
                <% end %>
              </li>
              <li class="nav-link p-8px">
                <%= link_to new_user_registration_path, class: 'd-flex align-items-center text-light text-decoration-none' do %>
                  <i class="fas fa-user-plus"></i>&nbsp;Sign up
                <% end %>
              </li>
              <li class="nav-link p-8px">
                <%= link_to new_user_session_path, class: 'd-flex align-items-center text-light text-decoration-none' do %>
                  <i class="fas fa-sign-in-alt"></i>&nbsp;Log in
                <% end %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <%= flash[:notice] %>

    <main class="mb-5">

      <%= yield %>
    </main>
    <footer>
      <div class="container">
        <row class="d-flex">
          <p class="mx-auto">CopyRight Infratop.inc</p>
        </row>
      </div>
    </footer>
  </body>
</html>